const postTypes = {
  ADD_FAVORITE: "ADD_FAVORITE",
  DELETE_FAVORITE: "DELETE_FAVORITE",
  ADD_BOOKMARK: "ADD_BOOKMARK",
  DELETE_BOOKMARK: "DELETE_BOOKMARK",
  REMOVE_SAVED_POSTS: "REMOVE_SAVED_POSTS"
};

export default postTypes;
